### ISSUE TITLE
Failed building basictad with `pip install -v -e .`

### ISSUE THREAD

**Issue by SilvioGiancola** [MCG-NJU/BasicTAD#15]
Hi,

I followed your guideline to build basictad:
```bash
conda create -y -n basictad python=3.8
conda activate basictad
conda install -y pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=10.2 -c pytorch
pip install mmcv-full==1.4 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html
pip install -r requirements/build.txt
pip install -v -e .
```

But the building of basictad returns this issue:
```
Using pip 23.0.1 from /home/giancos/anaconda3/envs/basictad/lib/python3.8/site-packages/pip (python 3.8)
Obtaining file:///home/giancos/git/BasicTAD
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Using cached setuptools-67.8.0-py3-none-any.whl (1.1 MB)
  Collecting wheel
    Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-67.8.0 wheel-0.40.0
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Getting requirements to build editable
  Traceback (most recent call last):
    File "/home/giancos/anaconda3/envs/basictad/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/giancos/anaconda3/envs/basictad/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/giancos/anaconda3/envs/basictad/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
      return hook(config_settings)
    File "/tmp/pip-build-env-ktgl8v87/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 450, in get_requires_for_build_editable
      return self.get_requires_for_build_wheel(config_settings)
    File "/tmp/pip-build-env-ktgl8v87/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-ktgl8v87/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-ktgl8v87/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-ktgl8v87/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 4, in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/giancos/anaconda3/envs/basictad/bin/python /home/giancos/anaconda3/envs/basictad/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_editable /tmp/tmp30uy9csl
  cwd: /home/giancos/git/BasicTAD
  Getting requirements to build editable ... error
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I ensured to have torch installed in my conda environment with:
```bash
(basictad) giancos@PC-KW-60110:~/git/BasicTAD$ python 
Python 3.8.16 (default, Mar  2 2023, 03:21:46) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```

Could you let me know where that installation failed? I tried on different workstations, a GPU cluster, and got the same error several times. Any insight is appreciated. Thanks

**Comment by yangmin666** [comment]
I admit that this code framework is not friendly to all machines, and I often encounter the similar problems on other machines. I have a suggestion: please downgrade the pip23 into pip20 and it maybe works.

**Comment by Architect-ll** [comment]
I encountered an issue while reproducing code: 4 | # include<torch/extension. h>

|^~~~~~~~~~~~~~~~~~~

Compilation terminated

I have never encountered such a situation before, how can I solve it. thanks

**Comment by Zerobub** [comment]
have you solved this problem
